<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="MUM-LAP-1086" name="tests.ATestToolkitCaseManagement" tests="5" failures="1" timestamp="07 Jun 2021 07:15:13 GMT" time="66.334" errors="0">
  <testcase name="TestLoginFunctionality" time="23.281" classname="tests.ATestToolkitCaseManagement"/>
  <testcase name="TestMailStatusChangedVerified" time="43.053" classname="tests.ATestToolkitCaseManagement">
    <failure type="java.lang.AssertionError" message="expected [Verified] but found [New Template]">
      <![CDATA[java.lang.AssertionError: expected [Verified] but found [New Template]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at main.EDRM.hybridFramework.helper.assertion.AssertionHelper.verifyText(AssertionHelper.java:25)
at tests.ATestToolkitCaseManagement.TestMailStatusChangedVerified(ATestToolkitCaseManagement.java:227)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TestMailStatusChangedVerified -->
  <testcase name="TestPartMatchTemplateChangesStatusMatchedFromPending" classname="tests.ATestToolkitCaseManagement">
    <skipped/>
  </testcase> <!-- TestPartMatchTemplateChangesStatusMatchedFromPending -->
  <testcase name="TestVerifyCaseSubDocAccessed" classname="tests.ATestToolkitCaseManagement">
    <skipped/>
  </testcase> <!-- TestVerifyCaseSubDocAccessed -->
  <testcase name="TestVerifyCaseCapturedSubDocAcceptance" classname="tests.ATestToolkitCaseManagement">
    <skipped/>
  </testcase> <!-- TestVerifyCaseCapturedSubDocAcceptance -->
</testsuite> <!-- tests.ATestToolkitCaseManagement -->
